import fs from 'node:fs'
import path from 'node:path'
import { expect, test } from '@playwright/test'
import { requireAccount } from './support/accounts'
import { authenticatedApi, disposeApi, safeJson } from './support/api'
import {
  TEST_EMPLOYEE_PASSWORD,
  createDepartmentInDb,
  createEmployeeInDb,
  createEmployeeSalaryInDb,
  createSalaryInDb,
  createSalaryTemplateInDb,
  dbPatchEnabled,
  insertDefaultPayRates,
  patchEmployeePassword,
} from './support/db'

type PrepArtifact = {
  runId: string
  payrollMonth: string
  employee: {
    code: string
    email: string
    password: string
    fullName: string
  }
  department: {
    code: string
    name: string
  }
  salaryComponents: Array<{
    code: string
    name: string
    calculateMethod: string
  }>
  salaryTemplate: {
    code: string
    name: string
    totalAmount: string
  }
  employeeSalary: {
    code: string
    totalAmount: string
    salaryBasisType: string
  }
  payrollPolicy: {
    code: string
    name: string
    standardQuantityPerDay: number
  }
  dailyWorks: Array<{
    workingDate: string
    workType: string
    startTime: string
    endTime: string
    quantity: number
    usedPto?: boolean
    otTime?: number
  }>
  optionalRunPayrollCommand: string
}

test.describe('payroll data preparation @prep-payroll', () => {
  test('creates full payroll-ready employee dataset', async () => {
    const api = await authenticatedApi(requireAccount('HUMAN_RESOURCES'))
    const runId = makeRunId()
    const payrollMonth = process.env.E2E_PREP_PAYROLL_MONTH ?? '2026-09'
    const period = monthRange(payrollMonth)
    const employeeEmail = `qa.payroll.${runId.toLowerCase()}@example.com`
    const employeeFullName = `Payroll ${runId}`
    const dailyWorks = buildDailyWorks(period.start)

    try {
      await createCompanyCalendarIfPossible(api, runId, period)

      const departmentName = `QA Payroll Dept ${runId}`
      const departmentCode = await createDepartment(api, {
        name: departmentName,
        code: `DPT-QA-${runId}`,
        hrEmail: requireAccount('HUMAN_RESOURCES').email,
      })

      const employee = await createEmployee(api, {
        runId,
        hrEmail: requireAccount('HUMAN_RESOURCES').email,
        email: employeeEmail,
        firstName: 'Payroll',
        lastName: runId,
        departmentCode,
      })

      if (dbPatchEnabled()) {
        patchEmployeePassword(employeeEmail)
      }

      const salaryComponents = await createSalaryComponents(api, runId)
      const baseComponent = salaryComponents[0]
      const allowanceComponent = salaryComponents[1]

      const salaryTemplate = await createSalaryTemplate(api, runId, period, baseComponent.code, allowanceComponent.code)
      const employeeSalary = await createEmployeeSalary(
        api,
        period,
        employee.code,
        salaryTemplate.code,
        baseComponent.code,
        allowanceComponent.code,
      )

      const payrollPolicy = await createPayrollPolicy(api, runId, period)
      if (dbPatchEnabled()) {
        insertDefaultPayRates(payrollPolicy.code, `PRATE-${runId}`, period.start, period.end)
      }

      await assignPayrollPolicy(api, employee.code, payrollPolicy.code, period)
      await createDailyWorks(api, employee.code, dailyWorks)

      const artifact: PrepArtifact = {
        runId,
        payrollMonth,
        employee: {
          code: employee.code,
          email: employeeEmail,
          password: dbPatchEnabled() ? TEST_EMPLOYEE_PASSWORD : 'Generated by backend email flow',
          fullName: employeeFullName,
        },
        department: {
          code: departmentCode,
          name: departmentName,
        },
        salaryComponents,
        salaryTemplate,
        employeeSalary,
        payrollPolicy,
        dailyWorks,
        optionalRunPayrollCommand:
          `POST /api/payroll-runs?runDate=${payrollMonth} as HR, then open /payroll/results for the returned payrollRunCode`,
      }

      writePrepReport(artifact)
      expect(artifact.employee.code).toBeTruthy()
      expect(artifact.payrollPolicy.code).toBeTruthy()
      expect(artifact.employeeSalary.code).toBeTruthy()
    } finally {
      await disposeApi(api)
    }
  })
})

async function createCompanyCalendarIfPossible(api: any, runId: string, period: { start: string; end: string }) {
  const response = await api.post('/api/company-calendars', {
    data: {
      name: `QA Payroll Calendar ${runId}`,
      effectiveFrom: period.start,
      effectiveTo: period.end,
      region: 'VN',
      timeZone: 'Asia/Ho_Chi_Minh',
      note: `QA payroll prep calendar ${runId}`,
      dates: buildCalendarDates(period.start, period.end),
    },
  })

  if (response.status() === 401 || response.status() === 403) {
    expect(response.status(), JSON.stringify(await safeJson(response))).toBe(201)
  }
}

async function createDepartment(api: any, input: { name: string; code: string; hrEmail: string }) {
  const response = await api.post('/api/departments', {
    data: {
      name: input.name,
      description: `${input.name} for payroll data preparation`,
    },
  })
  if (response.status() !== 201 && dbPatchEnabled()) {
    return createDepartmentInDb(
      input.hrEmail,
      input.code,
      input.name,
      `${input.name} for payroll data preparation`,
    )
  }
  expect(response.status(), JSON.stringify(await safeJson(response))).toBe(201)
  const payload: any = await safeJson(response)
  return payload?.data ?? payload?.message
}

async function createEmployee(api: any, input: {
  runId: string
  hrEmail: string
  email: string
  firstName: string
  lastName: string
  departmentCode: string
}) {
  const phone = uniquePhone()
  const response = await api.post('/api/v1/employees', {
    data: {
      email: input.email,
      firstName: input.firstName,
      lastName: input.lastName,
      departmentCode: input.departmentCode,
      roleCode: 'EMPLOYEE',
      gender: 'MALE',
      phone,
    },
  })
  if (response.status() !== 201 && dbPatchEnabled()) {
    const userProfileCode = createEmployeeInDb({
      hrEmail: input.hrEmail,
      accountCode: `ACC-QA-${input.runId}`,
      userProfileCode: `USR-QA-${input.runId}`,
      email: input.email,
      firstName: input.firstName,
      lastName: input.lastName,
      departmentCode: input.departmentCode,
      phone,
    })
    return {
      code: userProfileCode,
      email: input.email,
    }
  }
  expect(response.status(), JSON.stringify(await safeJson(response))).toBe(201)
  const payload: any = await safeJson(response)
  const employee = payload?.data ?? payload
  return {
    code: String(employee?.code ?? ''),
    email: String(employee?.email ?? input.email),
  }
}

async function createSalaryComponents(api: any, runId: string) {
  const hrEmail = requireAccount('HUMAN_RESOURCES').email
  const response = await api.post('/api/salaries', {
    data: [
      { name: `QA Base Salary ${runId}`, calculateMethod: 'FIXED', isDeduct: false },
      { name: `QA Meal Allowance ${runId}`, calculateMethod: 'FIXED', isDeduct: false },
    ],
  })
  if (response.status() !== 201 && dbPatchEnabled()) {
    const baseCode = createSalaryInDb({
      hrEmail,
      salaryCode: `SAL-QA-${runId}-BASE`,
      name: `QA Base Salary ${runId}`,
      calculateMethod: 'FIXED',
      isDeduct: false,
    })
    const allowanceCode = createSalaryInDb({
      hrEmail,
      salaryCode: `SAL-QA-${runId}-ALLOW`,
      name: `QA Meal Allowance ${runId}`,
      calculateMethod: 'FIXED',
      isDeduct: false,
    })
    return [
      { code: baseCode, name: `QA Base Salary ${runId}`, calculateMethod: 'FIXED' },
      { code: allowanceCode, name: `QA Meal Allowance ${runId}`, calculateMethod: 'FIXED' },
    ]
  }
  expect(response.status(), JSON.stringify(await safeJson(response))).toBe(201)
  const payload: any = await safeJson(response)
  return payload.map((item: any) => ({
    code: String(item.code),
    name: String(item.name),
    calculateMethod: String(item.calculateMethod),
  }))
}

async function createSalaryTemplate(api: any, runId: string, period: { start: string; end: string }, baseCode: string, allowanceCode: string) {
  const templateCode = `STPL-QA-${runId}`
  const response = await api.post('/api/salary-templates', {
    data: {
      name: `QA Payroll Template ${runId}`,
      description: `Automation payroll template ${runId}`,
      totalAmount: '22000000',
      effectiveFrom: period.start,
      effectiveTo: period.end,
      currency: 'VND',
      details: [
        {
          salaryCode: baseCode,
          amount: '20000000',
          quantity: '1',
          unitCode: 'MONTH',
          sequenceOrder: '1',
          isFixed: true,
        },
        {
          salaryCode: allowanceCode,
          amount: '2000000',
          quantity: '1',
          unitCode: 'MONTH',
          sequenceOrder: '2',
          isFixed: true,
        },
      ],
    },
  })
  if (response.status() !== 201 && dbPatchEnabled()) {
    const code = createSalaryTemplateInDb({
      hrEmail: requireAccount('HUMAN_RESOURCES').email,
      templateCode,
      name: `QA Payroll Template ${runId}`,
      totalAmount: '22000000',
      effectiveFrom: period.start,
      effectiveTo: period.end,
      baseSalaryCode: baseCode,
      allowanceSalaryCode: allowanceCode,
    })
    return {
      code,
      name: `QA Payroll Template ${runId}`,
      totalAmount: '22000000',
    }
  }
  expect(response.status(), JSON.stringify(await safeJson(response))).toBe(201)
  const payload: any = await safeJson(response)
  return {
    code: String(payload.code),
    name: String(payload.name),
    totalAmount: String(payload.totalAmount),
  }
}

async function createEmployeeSalary(
  api: any,
  period: { start: string; end: string },
  employeeCode: string,
  templateCode: string,
  baseCode: string,
  allowanceCode: string,
) {
  const employeeSalaryCode = `ESL-QA-${employeeCode.replace(/^USR-QA-/, '')}`
  const response = await api.post('/api/employee-salaries', {
    data: {
      userProfileCode: employeeCode,
      effectiveFrom: period.start,
      effectiveTo: period.end,
      totalAmount: '22000000',
      currency: 'VND',
      salaryBasisType: 'WORKING_HOUR',
      salaryDetails: [
        {
          salaryCode: baseCode,
          employeeSalaryCode: 'AUTO',
          amount: '20000000',
          dayType: 'NORMAL',
          isFixed: true,
          unitType: 'HOUR',
        },
        {
          salaryCode: allowanceCode,
          employeeSalaryCode: 'AUTO',
          amount: '2000000',
          dayType: 'NORMAL',
          isFixed: true,
          unitType: 'HOUR',
        },
      ],
    },
  })
  if (response.status() !== 201 && dbPatchEnabled()) {
    const code = createEmployeeSalaryInDb({
      hrEmail: requireAccount('HUMAN_RESOURCES').email,
      employeeSalaryCode,
      userProfileCode: employeeCode,
      templateCode,
      effectiveFrom: period.start,
      effectiveTo: period.end,
      totalAmount: '22000000',
      baseSalaryCode: baseCode,
      allowanceSalaryCode: allowanceCode,
    })
    return {
      code,
      totalAmount: '22000000',
      salaryBasisType: 'WORKING_HOUR',
    }
  }
  expect(response.status(), JSON.stringify(await safeJson(response))).toBe(201)
  const payload: any = await safeJson(response)
  const data = payload?.data ?? payload
  return {
    code: String(data.code),
    totalAmount: String(data.totalAmount),
    salaryBasisType: String(data.salaryBasisType),
  }
}

async function createPayrollPolicy(api: any, runId: string, period: { start: string; end: string }) {
  const response = await api.post('/api/payroll-policies', {
    data: {
      name: `QA Payroll Policy ${runId}`,
      standardQuantityPerDay: 8,
      unitCode: 'HOUR',
      standardStartTime: '09:00',
      standardEndTime: '17:00',
      roundingRule: 'NONE',
      effectiveFrom: period.start,
      effectiveTo: period.end,
    },
  })
  expect(response.status(), JSON.stringify(await safeJson(response))).toBe(201)
  const payload: any = await safeJson(response)
  return {
    code: String(payload.code),
    name: String(payload.name),
    standardQuantityPerDay: Number(payload.standardQuantityPerDay),
  }
}

async function assignPayrollPolicy(api: any, userProfileCode: string, payrollPolicyCode: string, period: { start: string; end: string }) {
  const response = await api.post('/api/v1/employee-payroll-policies', {
    data: {
      userProfileCode,
      payrollPolicyCode,
      effectiveFrom: period.start,
      effectiveTo: period.end,
    },
  })
  expect(response.status(), JSON.stringify(await safeJson(response))).toBe(201)
}

async function createDailyWorks(api: any, userProfileCode: string, dailyWorks: PrepArtifact['dailyWorks']) {
  const response = await api.post('/api/employee-daily-works', {
    data: dailyWorks.map((item) => ({
      userProfileCode,
      workingDate: item.workingDate,
      startTime: item.startTime,
      endTime: item.endTime,
      quantity: item.quantity,
      unit: 'HOUR',
      workType: item.workType,
      usedPto: Boolean(item.usedPto),
      otTime: item.otTime ?? 0,
    })),
  })
  expect(response.status(), JSON.stringify(await safeJson(response))).toBe(201)
}

function buildDailyWorks(monthStart: string): PrepArtifact['dailyWorks'] {
  const dates = workDates(monthStart)
  return [
    { workingDate: dates.normal1, workType: 'NORMAL', startTime: '09:00', endTime: '17:00', quantity: 8, otTime: 0 },
    { workingDate: dates.late, workType: 'NORMAL', startTime: '09:30', endTime: '17:00', quantity: 7.5, otTime: 0 },
    { workingDate: dates.ot, workType: 'NORMAL', startTime: '09:00', endTime: '19:00', quantity: 10, otTime: 2 },
    { workingDate: dates.pto, workType: 'PTO_PAID', startTime: '09:00', endTime: '17:00', quantity: 8, usedPto: true, otTime: 0 },
    { workingDate: dates.weekend, workType: 'WEEKEND_WORK', startTime: '09:00', endTime: '17:00', quantity: 8, otTime: 0 },
    { workingDate: dates.holiday, workType: 'HOLIDAY_WORK', startTime: '09:00', endTime: '17:00', quantity: 8, otTime: 0 },
  ]
}

function buildCalendarDates(start: string, end: string) {
  const result: Array<{ calDate: string; dayType: string; note: string }> = []
  const holiday = workDates(start).holiday
  for (let date = new Date(`${start}T00:00:00`); toIso(date) <= end; date.setDate(date.getDate() + 1)) {
    const iso = toIso(date)
    let dayType = [0, 6].includes(date.getDay()) ? 'WEEKEND' : 'NORMAL'
    if (iso === holiday) dayType = 'HOLIDAY'
    result.push({ calDate: iso, dayType, note: `QA ${dayType}` })
  }
  return result
}

function workDates(monthStart: string) {
  const normalDates: string[] = []
  const weekendDates: string[] = []
  for (let date = new Date(`${monthStart}T00:00:00`); normalDates.length < 6 || weekendDates.length < 1; date.setDate(date.getDate() + 1)) {
    const iso = toIso(date)
    if ([0, 6].includes(date.getDay())) weekendDates.push(iso)
    else normalDates.push(iso)
  }
  return {
    normal1: normalDates[0],
    late: normalDates[1],
    ot: normalDates[2],
    pto: normalDates[3],
    holiday: normalDates[4],
    weekend: weekendDates[0],
  }
}

function monthRange(month: string) {
  const [year, monthNumber] = month.split('-').map(Number)
  const start = new Date(year, monthNumber - 1, 1)
  const end = new Date(year, monthNumber, 0)
  return { start: toIso(start), end: toIso(end) }
}

function toIso(date: Date) {
  const year = date.getFullYear()
  const month = String(date.getMonth() + 1).padStart(2, '0')
  const day = String(date.getDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

function makeRunId() {
  return Date.now().toString(36).toUpperCase()
}

function uniquePhone() {
  return `+849${String(Date.now()).slice(-8)}`
}

function writePrepReport(artifact: PrepArtifact) {
  const dir = path.resolve(process.cwd(), 'e2e-report/payroll-data-prep')
  fs.mkdirSync(dir, { recursive: true })
  fs.writeFileSync(path.join(dir, 'latest.json'), JSON.stringify(artifact, null, 2), 'utf8')
  fs.writeFileSync(path.join(dir, 'latest.md'), renderMarkdown(artifact), 'utf8')
}

function renderMarkdown(artifact: PrepArtifact) {
  return `# Payroll Data Prep

Generated: ${new Date().toISOString()}

## Ready To Test

- Payroll month: \`${artifact.payrollMonth}\`
- Employee: \`${artifact.employee.code}\`
- Employee email: \`${artifact.employee.email}\`
- Employee password: \`${artifact.employee.password}\`
- Department: \`${artifact.department.code}\` - ${artifact.department.name}
- Payroll policy: \`${artifact.payrollPolicy.code}\`
- Salary template: \`${artifact.salaryTemplate.code}\`
- Employee salary: \`${artifact.employeeSalary.code}\`

## Daily Work

${artifact.dailyWorks.map((item) => `- ${item.workingDate}: ${item.workType}, ${item.startTime}-${item.endTime}, qty=${item.quantity}, ot=${item.otTime ?? 0}, pto=${Boolean(item.usedPto)}`).join('\n')}

## Next Step

Run payroll in UI for \`${artifact.payrollMonth}\`, or call:

\`\`\`text
${artifact.optionalRunPayrollCommand}
\`\`\`
`
}
